### ISSUE TITLE
change ArpaLombardia source

### ISSUE THREAD

**Issue by jobonaf** [jobonaf/calicantus#25]
Open Data are available:
* data are here https://www.dati.lombardia.it/Ambiente/Dati-sensori-aria/nicp-bhqi https://www.dati.lombardia.it/resource/2tw8-h2cp.json
* metadata are here https://www.dati.lombardia.it/Ambiente/Stazioni-qualit-dell-aria/ib47-atvt https://www.dati.lombardia.it/resource/t4f9-i4k5.json

**Comment by jobonaf** [comment]
Maybe registration is required to access recent data...
Alternative is very slow (300MB): 
https://www.dati.lombardia.it/api/views/nicp-bhqi/rows.json?accessType=DOWNLOAD

**Comment by dcrespi** [comment]
You're right.
You have to register to www.dati.lombardia.it and create a "token"
In our "italian" portale , after sign-up , go to you profile and create a token, somewhere called "applicazione".

using the token you will not suffer from throtteling.

Developers documentation can be found on https://dev.socrata.com/consumers/getting-started.html

If you have question feel free to write to admin@dati.lombardia.it

bye
Daniele Crespi

**Comment by jobonaf** [comment]
Thank you Daniele. After the registration, I created an application and I got the app token. I tested the access with R package `RSocrata`. It works.
I'm going to  work on this in the next days.

Bye
